-- 既存の users テーブルに Better Auth 用のカラムを追加
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE AFTER username,
  ADD COLUMN IF NOT EXISTS name VARCHAR(255) AFTER email,
  ADD COLUMN IF NOT EXISTS emailVerified BOOLEAN DEFAULT FALSE AFTER name,
  ADD COLUMN IF NOT EXISTS createdAt DATETIME DEFAULT CURRENT_TIMESTAMP AFTER emailVerified,
  ADD COLUMN IF NOT EXISTS updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER createdAt;

-- セッションテーブル（必須）
CREATE TABLE IF NOT EXISTS session (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  expiresAt DATETIME NOT NULL,
  token VARCHAR(255) NOT NULL UNIQUE,
  userId INT(11) UNSIGNED NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_token (token),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

-- アカウントテーブル（パスワード認証に必須）
CREATE TABLE IF NOT EXISTS account (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  accountId VARCHAR(255) NOT NULL,
  providerId VARCHAR(255) NOT NULL,
  userId INT(11) UNSIGNED NOT NULL,
  password TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_userId (userId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
